#!/usr/bin/env bash

run_step() {
	echo
	echo "  === $@ ==="
	echo
}

run_step "Provisioning Hadoop Development Environment"
sudo apt-get install -y software-properties-common

run_step "Installing Git"
sudo apt-get install -y git bash-completion

run_step "Setting up Oracle Java PPA"
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update

run_step "Installing Oracle Java 7"
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get install -y oracle-java7-installer

run_step "Installing Oracle Java 8"
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get install -y oracle-java8-installer

run_step "Installing Maven"
sudo apt-get install -y maven

run_step "Installing Native Libraries"
sudo apt-get install -y build-essential autoconf automake libtool cmake zlib1g-dev pkg-config libssl-dev

run_step "Installing ProtocolBuffer 2.5.0"
sudo apt-get install -y protobuf-compiler

run_step "Installing Snappy compression"
sudo apt-get install -y snappy libsnappy-dev

# run_step "Installing Intel ISA-L library for erasure coding"
#   Please refer to https://01.org/intel%C2%AE-storage-acceleration-library-open-source-version

run_step "Installing Bzip2"
sudo apt-get install -y bzip2 libbz2-dev

run_step "Installing Jansson (C Library for JSON)"
sudo apt-get install -y libjansson-dev

run_step "Installing Linux FUSE"
sudo apt-get install -y fuse libfuse-dev

# run_step "Installing Bats"
# git clone https://github.com/sstephenson/bats.git
# cd bats
# sudo ./install.sh /usr/local
